version: '3'
services:

  hk-mysql:
   container_name: mysql57
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_ROOT_PASSWORD: 1234
    MYSQL_USER: demo_java
    MYSQL_PASSWORD: 1234
    MYSQL_DATABASE: hello_java
   volumes:
    - ./food-service/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
   ports:
    - "3308:3308"
   restart: always

  food-service:
   restart: always
   build:
    context: ./food-service
   working_dir: /food-service
   container_name: food-service
   volumes:
    - ./food-service:/food-service
    - ~/.m2:/root/.m2
   expose:
    - "8080"
   ports:
    - "8080:8080"
   environment:
    - "SPRING_PROFILES_ACTIVE=dev"
   depends_on:
    - hk-mysql
