version: '3'
services:
  hk-mysql:
   container_name: hk-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: hellokoding
    MYSQL_ROOT_HOST: '%'
   ports:
    - "3306:3306"
   restart: always
  
  food-service:
   restart: always
   build:
    context: ./food-service
    args:
      - JAR_FILE=build/libs/food-service-0.0.1-SNAPSHOT.jar
   working_dir: /food-service
   container_name: food-service
   volumes:
    - ./food-service:/food-service
    - ~/.m2:/root/.m2
   expose:
    - "8080"
   ports:
    - "8080:8080"
   depends_on:
    - hk-mysql
