version: '3'

services:
  api:
    restart: always
    working_dir: /storefront
    build:
      context: ./storefront
    container_name: api-layer
    volumes:
      - ./storefront:/storefront
      - ~/.m2:/root/.m2
    ports:
      - "8081:8081"
