version: '3'

services:
  app:
    restart: always
    working_dir: /app
    build:
      context: ./vue-src
    container_name: app
    volumes:
      - ./vue-src:/vue-src
      - ~/.m2:/root/.m2
    ports:
      - "8082:8082"
