version: '3'

services:
  api:
    restart: always
    build:
      context: ./storefront
      args:
        - JAR_FILE=build/libs/storefront-0.0.1-SNAPSHOT.jar
    working_dir: /storefront
    volumes:
      - ./storefront:/storefront
      - ~/.m2:/root/.m2
    ports:
      - "8081:8081"
